/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.IS.marisqueria3.vista;

import com.IS.marisqueria3.services.*;
import com.IS.marisqueria3.model.ItemPedido;
import com.IS.marisqueria3.model.Pedido;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author ambro
 */
public class ICocina extends javax.swing.JFrame {
    private PedidoService pedidoS;;
    private ProductoService productoS;
    private Timer actualizador;
    /**
     * Creates new form ICocina
     */
    public ICocina() throws Exception {
        productoS= new ProductoService();
        pedidoS = new PedidoService();
        initComponents();
        iniciarActualizacion();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        scrollPedidos = new javax.swing.JScrollPane();
        listaPedidoP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cocina");

        jButton1.setText("Salir");

        jLabel1.setText("Lista de Pedidos");

        listaPedidoP.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout listaPedidoPLayout = new javax.swing.GroupLayout(listaPedidoP);
        listaPedidoP.setLayout(listaPedidoPLayout);
        listaPedidoPLayout.setHorizontalGroup(
            listaPedidoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        listaPedidoPLayout.setVerticalGroup(
            listaPedidoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        scrollPedidos.setViewportView(listaPedidoP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(303, 303, 303)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPedidos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(scrollPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void iniciarActualizacion() throws Exception{
        actualizador= new Timer(5000,e->{
            try {
                refrescarListaPedidos();
            } catch (Exception ex) {
                Logger.getLogger(ICocina.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        actualizador.start();
        refrescarListaPedidos();
    }
    
    public void refrescarListaPedidos() throws Exception{
        List<Pedido>pedidos= pedidoS.traerTodosPedidos("terminado");
        
        
        pedidos.sort(Comparator.comparing(Pedido::getEstado).reversed()//pendiente<preparado
            .thenComparing(Pedido::getEsUrgente).reversed()
                .thenComparing(Pedido::getFechaGeneracion).reversed());
        
        Collections.reverse(pedidos);
        mostrarPedidos(pedidos);
    }
    
   private void mostrarPedidos(List<Pedido> pedidos) throws Exception {
    listaPedidoP.removeAll();
    listaPedidoP.setLayout(new BoxLayout(listaPedidoP, BoxLayout.Y_AXIS));
    Font fontGrande = new Font("SansSerif", Font.PLAIN, 16); // Tamaño de fuente más grande

    for (Pedido pedido : pedidos) {
        JPanel panelPedido = new JPanel();
        panelPedido.setLayout(new BoxLayout(panelPedido, BoxLayout.Y_AXIS));
        panelPedido.setBorder(BorderFactory.createTitledBorder("🧾 Pedido #" + pedido.getNumeroPedido()));
        panelPedido.setBackground(pedido.getEsUrgente() ? new Color(255, 220, 220) : Color.WHITE);
        panelPedido.setMaximumSize(new Dimension(Integer.MAX_VALUE, 300));
        panelPedido.setAlignmentX(Component.LEFT_ALIGNMENT);

        JLabel lblInfo = new JLabel("🍽️ Cliente: " + pedido.getClienteId().getNombre()
            + " | " + (pedido.getEsUrgente() ? "⚠️ Urgente" : "Normal")
            + " | Estado: " + pedido.getEstado());
        lblInfo.setFont(fontGrande);

        JCheckBox chkPreparando = new JCheckBox("Preparando");
        JCheckBox chkTerminado = new JCheckBox("Terminado");
        chkPreparando.setFont(fontGrande);
        chkTerminado.setFont(fontGrande);

        if ("preparando".equals(pedido.getEstado())) {
            chkPreparando.setSelected(true);
            chkPreparando.setEnabled(false);
        }

        if ("terminado".equals(pedido.getEstado())) {
            chkPreparando.setEnabled(false);
            chkTerminado.setSelected(true);
            chkTerminado.setEnabled(false);
        }

        chkPreparando.addActionListener(e -> {
            if (chkPreparando.isSelected()) {
                try {
                    pedido.setEstado("preparando");
                    pedidoS.actualizarPedido(pedido);
                    refrescarListaPedidos();
                } catch (Exception ex) {
                    Logger.getLogger(ICocina.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        chkTerminado.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Estás seguro que deseas marcar el pedido como terminado?",
                "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                pedido.setEstado("terminado");
                try {
                    pedidoS.actualizarPedido(pedido);
                    refrescarListaPedidos();
                } catch (Exception ex) {
                    Logger.getLogger(ICocina.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                chkTerminado.setSelected(false); 
            }
        });

        panelPedido.add(lblInfo);
        panelPedido.add(chkPreparando);
        panelPedido.add(chkTerminado);

        // Productos del pedido
        JPanel panelProductos = new JPanel();
        panelProductos.setLayout(new BoxLayout(panelProductos, BoxLayout.Y_AXIS));
        panelProductos.setBackground(new Color(245, 245, 245));
        panelProductos.setBorder(BorderFactory.createTitledBorder("🧂 Productos del pedido"));
        panelProductos.setAlignmentX(Component.LEFT_ALIGNMENT);

        for (ItemPedido item : pedido.getItemPedidoList()) {
            JLabel lblProducto = new JLabel("🍽️ " + item.getProducto().getNombre() + " × " + item.getCantidad());
            lblProducto.setFont(fontGrande);
            lblProducto.setAlignmentX(Component.LEFT_ALIGNMENT);
            lblProducto.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));

            JLabel lblProductoDes = new JLabel("📝 Nota: " + item.getDescripcion());
            lblProductoDes.setFont(fontGrande);
            lblProductoDes.setAlignmentX(Component.LEFT_ALIGNMENT);
            lblProductoDes.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));

            panelProductos.add(lblProducto);
            panelProductos.add(lblProductoDes);
        }

        panelPedido.add(panelProductos);
        listaPedidoP.add(panelPedido);
        listaPedidoP.add(Box.createVerticalStrut(20)); // Espacio entre pedidos
    }

    listaPedidoP.revalidate();
    listaPedidoP.repaint();

    scrollPedidos.setViewportView(listaPedidoP);
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ICocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ICocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ICocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ICocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ICocina().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ICocina.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel listaPedidoP;
    private javax.swing.JScrollPane scrollPedidos;
    // End of variables declaration//GEN-END:variables

    
}
