/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.IS.marisqueria3.vista.IAdministradorC; 

import com.IS.marisqueria3.model.Ingrediente;
import com.IS.marisqueria3.model.MTablas.TMInventario;
import com.IS.marisqueria3.services.ProductoService;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractCellEditor;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class PanelInventario extends javax.swing.JPanel {
      
    private TMInventario tablaIngrediente;
    private ProductoService productoS;
    private List<DatosTablaInventario1> datosI;
    
    public PanelInventario() {
        productoS = new ProductoService();
        initComponents();
        cargarIngredientesEditar();
    }
    
    public void cargarIngredientesEditar() {
    datosI = new ArrayList<>();
    List<Ingrediente> ingredientes = productoS.listarIngredientes();
    
    for (Ingrediente i : ingredientes) {
        datosI.add(new DatosTablaInventario1(i));
    }
    
    tablaIngrediente = new TMInventario(datosI);
   
    ingredientesTabla2.setModel(tablaIngrediente);
    // En tu método cargarIngredientesEditar(), después de setModel:
    ingredientesTabla2.setRowHeight(30); // Cambia 30 por el valor deseado en píxeles
    // Configurar spinner correctamente
    TableColumn spinnerColumn = ingredientesTabla2.getColumnModel().getColumn(5);
    
    // Usar el mismo modelo para todos los spinners
    SpinnerNumberModel spinnerModel = new SpinnerNumberModel(0, -1000, 1000, 1);
    
    spinnerColumn.setCellEditor(new SpinnerEditor(spinnerModel));
    spinnerColumn.setCellRenderer(new SpinnerRenderer(spinnerModel));
    
    // Asegurar que los cambios se propaguen al modelo
    ingredientesTabla2.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
    ajustarAnchosColumnas();
    ingredientesTabla2.revalidate();
    ingredientesTabla2.repaint();
}
    
    private void ajustarAnchosColumnas() {
        TableColumnModel columnModel = ingredientesTabla2.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(150); // Nombre
        columnModel.getColumn(1).setPreferredWidth(100); // Stock mínimo
        columnModel.getColumn(2).setPreferredWidth(100); // Stock actual
        columnModel.getColumn(3).setPreferredWidth(80);  // Unidad M
        columnModel.getColumn(4).setPreferredWidth(120); // Precio x Unidad
        columnModel.getColumn(5).setPreferredWidth(150); // Ingresar/Merma
    }
    

    class SpinnerEditor extends AbstractCellEditor implements TableCellEditor {
    private final JSpinner spinner;

    public SpinnerEditor(SpinnerModel model) {
        spinner = new JSpinner(model);
        
        // Guardar cambios inmediatamente al cambiar valor
        spinner.addChangeListener(e -> stopCellEditing());
    }

    @Override
    public Object getCellEditorValue() {
        return spinner;
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value, 
            boolean isSelected, int row, int column) {
        spinner.setValue(value != null ? ((JSpinner) value).getValue() : 0);
        return spinner;
    }
}

class SpinnerRenderer implements TableCellRenderer {
    private final JSpinner spinner;

    public SpinnerRenderer(SpinnerModel model) {
        spinner = new JSpinner(model);
        spinner.setEnabled(true);  // Solo para visualización
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        if (value instanceof JSpinner) {
            spinner.setValue(((JSpinner) value).getValue());
        }
        
        // Estilos de selección
        if (isSelected) {
            spinner.setBackground(table.getSelectionBackground());
        } else {
            spinner.setBackground(table.getBackground());
        }
        
        return spinner;
    }
}


    
    



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ingredientesTabla2 = new javax.swing.JTable();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ingreso / Merma de Inventario");

        ingredientesTabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(ingredientesTabla2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(293, 293, 293))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ingredientesTabla2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
